// backend/controllers/orderController.js
const Order = require('../models/Order');
const Product = require('../models/Product');
const ErrorResponse = require('../utils/errorResponse');

// @desc    Create new order
// @route   POST /api/orders
// @access  Private
exports.createOrder = async (req, res, next) => {
  try {
    const {
      items,
      shippingInfo,
      paymentMethod = 'cash_on_delivery'
    } = req.body;

    console.log('🔄 Creating new order for user:', req.user.id);
    console.log('📦 Order items:', items);
    console.log('🏠 Shipping info:', shippingInfo);

    // Validate items array
    if (!items || !Array.isArray(items) || items.length === 0) {
      return next(new ErrorResponse('No items in order', 400));
    }

    // Calculate prices
    let itemsPrice = 0;
    const orderItems = [];

    // Process each item
    for (const item of items) {
      const product = await Product.findById(item.product);
      
      if (!product) {
        return next(new ErrorResponse(`Product not found: ${item.product}`, 404));
      }

      if (!item.quantity || item.quantity < 1) {
        return next(new ErrorResponse('Invalid quantity for order item', 400));
      }

      console.log(`📦 Processing product: ${product.name}, Stock: ${product.stock}, Requested: ${item.quantity}`);

      let selectedVariant = null;
      if (product.variants && product.variants.length > 0) {
        if (item.variantId) {
          selectedVariant = product.variants.id(item.variantId) || product.variants.find(v => v._id.toString() === item.variantId);
        }
        if (!selectedVariant && item.size) {
          selectedVariant = product.variants.find(v => v.size === item.size && (!item.color || v.color === item.color));
        }

        if (!selectedVariant) {
          return next(new ErrorResponse(`Selected product variant is not available for ${product.name}`, 400));
        }

        if (!selectedVariant.isActive) {
          return next(new ErrorResponse(`Selected product variant is not active for ${product.name}`, 400));
        }

        if (selectedVariant.stock < item.quantity) {
          return next(new ErrorResponse(`Insufficient stock for ${product.name} variant. Only ${selectedVariant.stock} available`, 400));
        }
      } else {
        if (product.stock < item.quantity) {
          return next(new ErrorResponse(`Insufficient stock for ${product.name}. Only ${product.stock} available`, 400));
        }
      }

      const itemPrice = selectedVariant?.price || product.price;
      itemsPrice += itemPrice * item.quantity;

      orderItems.push({
        product: item.product,
        variantId: selectedVariant ? selectedVariant._id.toString() : undefined,
        name: product.name,
        image: selectedVariant?.image?.url || product.images[0]?.url || '/images/default-product.jpg',
        price: itemPrice,
        size: selectedVariant?.size || item.size,
        color: selectedVariant?.color || item.color,
        sku: selectedVariant?.sku,
        quantity: item.quantity
      });

      // Update stock on variant or product
      if (selectedVariant) {
        selectedVariant.stock -= item.quantity;
      } else {
        product.stock -= item.quantity;
      }
      await product.save();
      console.log(`✅ Stock updated for ${product.name}: ${product.stock + item.quantity} -> ${product.stock}`);
    }

    // Calculate taxes and shipping (15% tax, 50 Birr shipping)
    const taxPrice = itemsPrice * 0.15;
    const shippingPrice = 50;
    const totalPrice = itemsPrice + taxPrice + shippingPrice;

    console.log('💰 Price calculation:', {
      itemsPrice,
      taxPrice,
      shippingPrice,
      totalPrice
    });

    // Create order - orderId will be auto-generated by pre-save middleware
    const orderData = {
      user: req.user.id,
      items: orderItems,
      shippingInfo,
      paymentInfo: {
        method: paymentMethod,
        status: paymentMethod === 'cash_on_delivery' ? 'pending' : 'processing'
      },
      itemsPrice,
      taxPrice,
      shippingPrice,
      totalPrice,
      orderStatus: 'pending'
    };

    console.log('📝 Creating order with data:', orderData);

    const order = await Order.create(orderData);

    console.log('✅ Order created successfully:', order.orderId);

    // Populate the order with user and product details
    await order.populate('user', 'name email');
    await order.populate('items.product', 'name images');

    res.status(201).json({
      success: true,
      message: 'Order created successfully',
      order
    });
  } catch (error) {
    console.error('❌ Error creating order:', error);
    
    // Handle specific mongoose validation errors
    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map(val => val.message);
      return next(new ErrorResponse(`Validation Error: ${messages.join(', ')}`, 400));
    }
    
    // Handle duplicate key errors
    if (error.code === 11000) {
      return next(new ErrorResponse('Duplicate order ID generated. Please try again.', 400));
    }
    
    next(error);
  }
};


// @desc    Get single order
// @route   GET /api/orders/:id
// @access  Private
exports.getOrder = async (req, res, next) => {
  try {
    const order = await Order.findById(req.params.id).populate('user', 'name email');

    if (!order) {
      return next(new ErrorResponse('Order not found', 404));
    }

    // Make sure user owns order or is admin
    if (order.user._id.toString() !== req.user.id && req.user.role !== 'admin') {
      return next(new ErrorResponse('Not authorized to access this order', 401));
    }

    res.status(200).json({
      success: true,
      order
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get logged in user orders
// @route   GET /api/orders/myorders
// @access  Private
exports.getMyOrders = async (req, res, next) => {
  try {
    const orders = await Order.find({ user: req.user.id }).sort('-createdAt');

    res.status(200).json({
      success: true,
      count: orders.length,
      orders
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get all orders (Admin)
// @route   GET /api/orders
// @access  Private/Admin
exports.getOrders = async (req, res, next) => {
  try {
    const { page = 1, limit = 10, search, status, sort } = req.query;

    const query = {};

    // 1. Status filter
    if (status && status !== 'all') {
      query.orderStatus = status;
    }

    // 2. Search filter
    if (search) {
      // Find users matching search term to include in order query
      const User = require('../models/User'); // ensure User is available
      const users = await User.find({
        $or: [
          { name: { $regex: search, $options: 'i' } },
          { email: { $regex: search, $options: 'i' } }
        ]
      }).select('_id');
      const userIds = users.map(u => u._id);

      query.$or = [
        { orderId: { $regex: search, $options: 'i' } },
        { 'shippingInfo.firstName': { $regex: search, $options: 'i' } },
        { 'shippingInfo.lastName': { $regex: search, $options: 'i' } },
        { 'shippingInfo.phoneNumber': { $regex: search, $options: 'i' } }
      ];

      if (userIds.length > 0) {
        query.$or.push({ user: { $in: userIds } });
      }
    }

    // 3. Stats calculation
    // Calculate global stats before pagination
    const allOrders = await Order.find();
    
    // Urgent logic: pending and created > 2 hours ago
    const twoHoursAgo = new Date(Date.now() - 2 * 60 * 60 * 1000);
    const urgentCount = await Order.countDocuments({
      orderStatus: 'pending',
      createdAt: { $lte: twoHoursAgo }
    });

    const stats = {
      total: allOrders.length,
      pending: allOrders.filter(o => o.orderStatus === 'pending').length,
      processing: allOrders.filter(o => o.orderStatus === 'processing').length,
      shipped: allOrders.filter(o => o.orderStatus === 'shipped').length,
      delivered: allOrders.filter(o => o.orderStatus === 'delivered').length,
      urgent: urgentCount
    };

    const totalAmount = allOrders.reduce((acc, order) => acc + order.totalPrice, 0);

    // 4. Pagination & Fetch
    const pageNum = parseInt(page);
    const limitNum = parseInt(limit);
    const skip = (pageNum - 1) * limitNum;

    // Default sort by -createdAt
    let sortObj = { createdAt: -1 };
    if (sort) {
       // if sort parameter is passed like "totalPrice" or "-totalPrice"
       // not strictly asked for, but good to have
    }

    const total = await Order.countDocuments(query);
    const pages = Math.ceil(total / limitNum);

    const orders = await Order.find(query)
      .populate('user', 'name email')
      .sort(sortObj)
      .skip(skip)
      .limit(limitNum);

    res.status(200).json({
      success: true,
      count: orders.length,
      totalAmount,
      orders, // kept for backward compatibility if any other frontend uses it
      data: orders,
      pagination: {
        page: pageNum,
        limit: limitNum,
        total,
        pages,
        hasNextPage: pageNum < pages,
        hasPrevPage: pageNum > 1
      },
      stats
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update order status
// @route   PUT /api/orders/:id/status
// @access  Private/Admin
exports.updateOrderStatus = async (req, res, next) => {
  try {
    const { status } = req.body;

    const order = await Order.findById(req.params.id);

    if (!order) {
      return next(new ErrorResponse('Order not found', 404));
    }

    order.orderStatus = status;
    
    if (status === 'delivered') {
      order.deliveredAt = Date.now();
    }

    await order.save();

    res.status(200).json({
      success: true,
      order
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Delete order
// @route   DELETE /api/orders/:id
// @access  Private/Admin
exports.deleteOrder = async (req, res, next) => {
  try {
    const order = await Order.findById(req.params.id);

    if (!order) {
      return next(new ErrorResponse('Order not found', 404));
    }

    // Restore product stock
    for (const item of order.items) {
      const product = await Product.findById(item.product);
      if (product) {
        product.stock += item.quantity;
        await product.save();
      }
    }

    await Order.findByIdAndDelete(req.params.id);

    res.status(200).json({
      success: true,
      message: 'Order deleted successfully'
    });
  } catch (error) {
    next(error);
  }
};