// backend/controllers/orderController.js
const Order = require('../models/Order');
const Product = require('../models/Product');
const ErrorResponse = require('../utils/errorResponse');

// @desc    Create new order
// @route   POST /api/orders
// @access  Private
exports.createOrder = async (req, res, next) => {
  try {
    const {
      items,
      shippingInfo,
      paymentMethod = 'cash_on_delivery'
    } = req.body;

    console.log('🔄 Creating new order for user:', req.user.id);
    console.log('📦 Order items:', items);
    console.log('🏠 Shipping info:', shippingInfo);

    // Validate items array
    if (!items || !Array.isArray(items) || items.length === 0) {
      return next(new ErrorResponse('No items in order', 400));
    }

    // Calculate prices
    let itemsPrice = 0;
    const orderItems = [];

    // Process each item
    for (const item of items) {
      const product = await Product.findById(item.product);
      
      if (!product) {
        return next(new ErrorResponse(`Product not found: ${item.product}`, 404));
      }

      console.log(`📦 Processing product: ${product.name}, Stock: ${product.stock}, Requested: ${item.quantity}`);

      if (product.stock < item.quantity) {
        return next(new ErrorResponse(`Insufficient stock for ${product.name}. Only ${product.stock} available`, 400));
      }

      const itemTotal = product.price * item.quantity;
      itemsPrice += itemTotal;

      orderItems.push({
        product: item.product,
        name: product.name,
        image: product.images[0]?.url || '/images/default-product.jpg',
        price: product.price,
        size: item.size,
        quantity: item.quantity
      });

      // Update product stock
      product.stock -= item.quantity;
      await product.save();
      console.log(`✅ Stock updated for ${product.name}: ${product.stock + item.quantity} -> ${product.stock}`);
    }

    // Calculate taxes and shipping (15% tax, 50 Birr shipping)
    const taxPrice = itemsPrice * 0.15;
    const shippingPrice = 50;
    const totalPrice = itemsPrice + taxPrice + shippingPrice;

    console.log('💰 Price calculation:', {
      itemsPrice,
      taxPrice,
      shippingPrice,
      totalPrice
    });

    // Create order - orderId will be auto-generated by pre-save middleware
    const orderData = {
      user: req.user.id,
      items: orderItems,
      shippingInfo,
      paymentInfo: {
        method: paymentMethod,
        status: paymentMethod === 'cash_on_delivery' ? 'pending' : 'processing'
      },
      itemsPrice,
      taxPrice,
      shippingPrice,
      totalPrice,
      orderStatus: 'pending'
    };

    console.log('📝 Creating order with data:', orderData);

    const order = await Order.create(orderData);

    console.log('✅ Order created successfully:', order.orderId);

    // Populate the order with user and product details
    await order.populate('user', 'name email');
    await order.populate('items.product', 'name images');

    res.status(201).json({
      success: true,
      message: 'Order created successfully',
      order
    });
  } catch (error) {
    console.error('❌ Error creating order:', error);
    
    // Handle specific mongoose validation errors
    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map(val => val.message);
      return next(new ErrorResponse(`Validation Error: ${messages.join(', ')}`, 400));
    }
    
    // Handle duplicate key errors
    if (error.code === 11000) {
      return next(new ErrorResponse('Duplicate order ID generated. Please try again.', 400));
    }
    
    next(error);
  }
};


// @desc    Get single order
// @route   GET /api/orders/:id
// @access  Private
exports.getOrder = async (req, res, next) => {
  try {
    const order = await Order.findById(req.params.id).populate('user', 'name email');

    if (!order) {
      return next(new ErrorResponse('Order not found', 404));
    }

    // Make sure user owns order or is admin
    if (order.user._id.toString() !== req.user.id && req.user.role !== 'admin') {
      return next(new ErrorResponse('Not authorized to access this order', 401));
    }

    res.status(200).json({
      success: true,
      order
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get logged in user orders
// @route   GET /api/orders/myorders
// @access  Private
exports.getMyOrders = async (req, res, next) => {
  try {
    const orders = await Order.find({ user: req.user.id }).sort('-createdAt');

    res.status(200).json({
      success: true,
      count: orders.length,
      orders
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get all orders (Admin)
// @route   GET /api/orders
// @access  Private/Admin
exports.getOrders = async (req, res, next) => {
  try {
    const orders = await Order.find()
      .populate('user', 'name email')
      .sort('-createdAt');

    const totalAmount = orders.reduce((acc, order) => acc + order.totalPrice, 0);

    res.status(200).json({
      success: true,
      count: orders.length,
      totalAmount,
      orders
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Update order status
// @route   PUT /api/orders/:id/status
// @access  Private/Admin
exports.updateOrderStatus = async (req, res, next) => {
  try {
    const { status } = req.body;

    const order = await Order.findById(req.params.id);

    if (!order) {
      return next(new ErrorResponse('Order not found', 404));
    }

    order.orderStatus = status;
    
    if (status === 'delivered') {
      order.deliveredAt = Date.now();
    }

    await order.save();

    res.status(200).json({
      success: true,
      order
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Delete order
// @route   DELETE /api/orders/:id
// @access  Private/Admin
exports.deleteOrder = async (req, res, next) => {
  try {
    const order = await Order.findById(req.params.id);

    if (!order) {
      return next(new ErrorResponse('Order not found', 404));
    }

    // Restore product stock
    for (const item of order.items) {
      const product = await Product.findById(item.product);
      if (product) {
        product.stock += item.quantity;
        await product.save();
      }
    }

    await Order.findByIdAndDelete(req.params.id);

    res.status(200).json({
      success: true,
      message: 'Order deleted successfully'
    });
  } catch (error) {
    next(error);
  }
};